import { Button } from "../../../components/Button";
import { Header } from "../../../components/Header";
import { TalentSidebar } from "../../../components/TalentSidebar";

const draftQuestions = ["Build an accessible modal", "Investigate a layout shift", "Improve a responsive data table"];

export default function CreateAssessmentPage() {
  return <main className="screen talent-screen"><Header /><div className="talent-layout"><TalentSidebar active="All Assessments" /><section className="creator-layout"><div className="creator-main"><header><h1>Create an assessment</h1><p>Set the purpose, timing, and candidate experience before adding questions.</p></header>
    <section className="creator-card"><div className="section-row"><div><h2>Test details</h2><p>Give your assessment a clear name and decide when candidates can access it.</p></div><span>✓ Saved</span></div><div className="creator-form"><label>ASSESSMENT NAME<input value="Senior Frontend Engineer assessment" readOnly /></label><label>SCORE THRESHOLD<input value="75/100" readOnly /></label><label className="wide">DESCRIPTION<input value="Evaluate practical frontend skills, debugging approach, and communication." readOnly /></label><label>DURATION<input value="60 minutes" readOnly /></label><label>OPENS<input value="Mon, 14 Jul · 09:00" readOnly /></label><label>CLOSES<input value="Fri, 18 Jul · 18:00" readOnly /></label></div></section>
    <section className="creator-card questions-builder"><div className="section-row"><div><h2>Questions</h2><p>InterviewOS has turned your brief into an interview-ready question set.</p></div><button>＋</button></div><div className="coverage-grid"><span>SKILL COVERAGE<strong>High</strong><small>React · Debugging</small></span><span>TIME BUDGET<strong>60 min</strong><small>Within target</small></span></div>{draftQuestions.map((q,i)=><article key={q}><b>{i+1}</b><div><strong>{q}</strong><small>{i===0?"React · Medium · 15 min":i===1?"Debugging · Medium · 20 min":"CSS · Medium · 25 min"}</small></div><span>{i===2?"Building…":"Ready"}⌄</span></article>)}</section><p className="autosave-note"><strong>Ready when you are</strong><br/>Your progress is saved automatically.</p></div>
    <aside className="agent-panel"><div className="agent-message"><span>✦ Thought for 4s · 3 steps</span><p>I’ll draft three focused questions that reflect the role and the time limit, with space for candidates to explain their thinking.</p><button>Make accessibility essential</button><button>Keep the coding focus</button></div><div className="agent-reply">Keep Coding Focus</div><div className="agent-message"><span>✦ Thought for 4s · 3 steps</span><p>I balanced difficulty and timing so every question gives you a clear signal at senior level.</p><button>Draft Questions</button></div><div className="agent-message"><span>✦ Thought for 2m 12s · 8 steps</span><p>Created a set of 3 questions for the front-end developer assessment.</p><button>Release Assessment</button></div><div className="agent-composer"><input placeholder="Describe the app you want to build" /><div><span>＋</span><span>◉ GPT 4.0 Mini⌄</span><button>➤</button></div></div></aside>
  </section></div></main>;
}
